[package]
name = "mepeyew"
version = "0.1.4"
edition = "2021"
description = "mepeyew - Small But Powerful Graphics Library"
repository = "https://github.com/davnotdev/mepeyew"
homepage = "https://github.com/davnotdev/mepeyew"
license = "BSD-2-Clause"
keywords = ["gamedev", "graphics"]

[features]
default = [
    # "vulkan",
    "webgpu",
    "assert_extensions",
    "surface_extension",
]
vulkan = ["dep:ash", "dep:gpu-allocator", "dep:raw-window-metal"]
webgpu = ["dep:wasm-bindgen", "dep:web-sys", "dep:js-sys"]
assert_extensions = []
surface_extension = ["dep:raw-window-handle"]

[dev-dependencies]
winit = "0.28.1"
stb_image_rust = "2.27.2"
console_error_panic_hook = "0.1"

[dependencies]
#  vulkan
ash = { version = "0.37.0", optional = true }
gpu-allocator = { version = "0.21.0", optional = true }

#  surface_extension
raw-window-handle = { version = "0.5.0", optional = true }

#  shader_reflection_extension
spirv-reflect = { version = "0.2.3", optional = true }

#  webgpu
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", features = ["console", "Document", "Window", "Element", "Navigator", "Gpu", "GpuAdapter", "GpuDevice", "GpuCanvasContext", "HtmlCanvasElement", "GpuCanvasConfiguration", "GpuTextureFormat", "GpuCanvasAlphaMode", "GpuBuffer", "GpuBufferDescriptor", "GpuCommandEncoder", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuDepthStencilState", "GpuFragmentState", "GpuPrimitiveState", "GpuVertexState", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuBindGroupLayout", "GpuBindGroupLayoutDescriptor", "GpuBufferBindingLayout", "GpuTextureBindingLayout", "GpuSamplerBindingLayout", "GpuBufferBindingType", "GpuBindGroup", "GpuBindGroupDescriptor", "GpuBindGroupLayoutEntry", "GpuBindGroupEntry", "GpuPrimitiveState", "GpuCullMode", "GpuFrontFace", "GpuPrimitiveTopology", "GpuCompareFunction", "GpuColorTargetState", "GpuRenderPassEncoder", "GpuRenderPassDescriptor", "GpuQueue", "GpuCommandBuffer", "GpuRenderPassColorAttachment", "GpuRenderPassDepthStencilAttachment", "GpuLoadOp", "GpuStoreOp", "GpuTextureView", "GpuTexture", "GpuTextureDescriptor", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuVertexBufferLayout", "GpuVertexFormat", "GpuVertexAttribute", "GpuIndexFormat", "GpuColorDict", "GpuSampler", "GpuSamplerDescriptor", "GpuAddressMode", "GpuFilterMode", "GpuImageCopyTexture", "GpuImageDataLayout", "GpuBufferBinding", "GpuTextureSampleType"], optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
#  vulkan
raw-window-metal = { version = "0.3", optional = true }

[workspace]
members = [
    "run_wasm"
]
