[package]
name = "mepeyew"
version = "0.2.0"
edition = "2021"
description = "mepeyew - Small But Powerful Graphics Library"
repository = "https://github.com/davnotdev/mepeyew"
homepage = "https://github.com/davnotdev/mepeyew"
license = "BSD-2-Clause"
keywords = ["gamedev", "graphics"]

[features]
default = [
    "vulkan",
    "webgpu",
    "surface_extension",
    "naga_translation",
]
vulkan = ["dep:ash", "dep:gpu-allocator", "dep:raw-window-metal"]
webgpu = ["dep:wasm-bindgen", "dep:web-sys", "dep:js-sys"]
surface_extension = ["dep:raw-window-handle"]
naga_translation = ["dep:naga"]

[dev-dependencies]
winit = "0.28.1"
nalgebra-glm = "0.18"
stb_image_rust = "2.27.2"
console_error_panic_hook = "0.1"

[dependencies]
#  surface_extension
raw-window-handle = { version = "0.5.0", optional = true }

#  naga_translation
naga = { version = "0.12", features = ["glsl-in", "spv-in", "wgsl-in", "spv-out", "wgsl-out"], optional = true }

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
#  vulkan
ash = { version = "0.37.0", optional = true }
gpu-allocator = { version = "0.21.0", optional = true }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
#  vulkan
raw-window-metal = { version = "0.3", optional = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
#  webgpu
js-sys = { version = "0.3", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
web-sys = { version = "0.3", features = ["console", "Document", "Window", "Element", "Navigator", "Gpu", "GpuAdapter", "GpuDevice", "GpuCanvasContext", "HtmlCanvasElement", "GpuCanvasConfiguration", "GpuTextureFormat", "GpuCanvasAlphaMode", "GpuBuffer", "GpuBufferDescriptor", "GpuCommandEncoder", "GpuRenderPipeline", "GpuRenderPipelineDescriptor", "GpuDepthStencilState", "GpuFragmentState", "GpuPrimitiveState", "GpuVertexState", "GpuShaderModule", "GpuShaderModuleDescriptor", "GpuBindGroupLayout", "GpuBindGroupLayoutDescriptor", "GpuBufferBindingLayout", "GpuTextureBindingLayout", "GpuSamplerBindingLayout", "GpuBufferBindingType", "GpuBindGroup", "GpuBindGroupDescriptor", "GpuBindGroupLayoutEntry", "GpuBindGroupEntry", "GpuPrimitiveState", "GpuCullMode", "GpuFrontFace", "GpuPrimitiveTopology", "GpuCompareFunction", "GpuColorTargetState", "GpuRenderPassEncoder", "GpuRenderPassDescriptor", "GpuQueue", "GpuCommandBuffer", "GpuRenderPassColorAttachment", "GpuRenderPassDepthStencilAttachment", "GpuLoadOp", "GpuStoreOp", "GpuTextureView", "GpuTextureViewDescriptor", "GpuTexture", "GpuTextureDescriptor", "GpuPipelineLayout", "GpuPipelineLayoutDescriptor", "GpuVertexBufferLayout", "GpuVertexFormat", "GpuVertexAttribute", "GpuIndexFormat", "GpuColorDict", "GpuSampler", "GpuSamplerDescriptor", "GpuAddressMode", "GpuFilterMode", "GpuImageCopyTexture", "GpuImageDataLayout", "GpuBufferBinding", "GpuTextureSampleType", "GpuStencilFaceState", "GpuStencilOperation", "GpuMultisampleState", "GpuBlendState", "GpuBlendComponent", "GpuBlendFactor", "GpuBlendOperation", "GpuExtent3dDict", "GpuImageCopyTexture", "GpuMipmapFilterMode", "GpuComputePipeline", "GpuComputePipelineDescriptor", "GpuProgrammableStage", "GpuComputePassEncoder", "GpuSupportedLimits"], optional = true }

[workspace]
members = [
    "run_wasm"
]
